<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sparxie.Contracts\Sparxie.Contracts.csproj" />
    <ProjectReference Include="..\Sparxie.Infrastructure\Sparxie.Infrastructure.csproj" />
    <ProjectReference Include="..\Sparxie.LauncherCore\Sparxie.LauncherCore.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
